version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: racer_rin_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: racer_rin
      MYSQL_USER: racerrin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
